---
- import_tasks: ../shared/tasks/install_docker.yml
- import_tasks: ./ssl_setup_directories.yml

- name: Create config file
  become: yes
  copy:
    content: |
      dns_ovh_endpoint = ovh-eu
      dns_ovh_application_key = {{ ovh_application_id }}
      dns_ovh_application_secret = {{ ovh_application_secret }}
      dns_ovh_consumer_key = {{ ovh_consumer_key }}
    dest: /opt/certbot/config/ovh.ini

- name: Run certbot
  become: yes
  community.docker.docker_container:
    image: certbot/dns-ovh
    name: certbot
    volumes:
      - "/opt/certbot/certs:/etc/letsencrypt"
      - "/opt/certbot/config/ovh.ini:/opt/ovh.ini"
    state: started
    auto_remove: yes
    command: 
      - "certonly"
      - "--email chrisweaver1@pm.me"
      - "--dns-ovh --agree-tos"
      - "-d weav.ovh,*.weav.ovh -n"
      - "--dns-ovh-credentials /opt/ovh.ini"