---
- hosts: localhost

  vars_prompt:
    - name: config_volume
      prompt: "Enter config volume name or path: "
      private: no
      default: rutorrent_config
    - name: downloads_volume
      prompt: "Enter downloads volume name or path: " 
      private: no
      default: rutorrent_downloads
    - name: data_volume
      prompt: "Enter data volume name or path: " 
      private: no
      default: rutorrent_data

  tasks:
    - import_tasks: ../../playbooks/shared/tasks/install_docker.yml

    - name: Ensure rutorrent is running
      community.docker.docker_container:
        image: ghcr.io/linuxserver/rutorrent:latest
        name: rutorrent
        detach: yes
        env:
          PUID: "1000"
          PGID: "1000"
        ports:
          - "80:80"
          - "5000:5000"
          - "51413:51413"
          - "6881:6881/udp"
        networks:
          - name: weavc_net
        volumes:
          - "{{ config_volume }}:/config"
          - "{{ downloads_volume }}:/downloads"
          - "{{ data_volume }}:/data"
        restart_policy: unless-stopped
        state: started
