---
- import_tasks: ./provision_deployment.yml

- name: Docker compose up
  community.docker.docker_compose:
    project_src: /opt/trunk/
    restarted: yes
  register: output

# - ansible.builtin.debug:
#   var: output