theme: jekyll-theme-minimal
source: .
destination: _site
exclude:
- Gemfile
- Gemfile.lock
- nginx.conf
- node_modules/
- .devcontainer/
kramdown:
    syntax_highlighter_opts:
        line_numbers: false
        tab_width: 2
        css: class
hide_details: false
hide_name: false
hide_email: false
