---
- hosts: all

  handlers:
    - name: restart ssh
      service: name=sshd state=restarted

  tasks:
    - import_tasks: ../shared/tasks/ssh_config.yml
    - import_tasks: ../shared/tasks/install_docker.yml
    - import_tasks: ../ssl/tasks/ssl_setup_copy.yml
    - import_tasks: ./tasks/deploy_services.yml