---
- name: Add directory
  file:    
    path: '{{ paths.dev }}/{{ item }}'
    state: directory
  with_items:
    - proj
    - builds
    - misc
- import_tasks: ./install_docker.yml
- import_tasks: ./install_python.yml
- import_tasks: ./install_go.yml
- import_tasks: ./install_dotnet.yml
- import_tasks: ./install_node.yml
- import_tasks: ./install_rust.yml