---
- import_tasks: ./install_python.yml

- name: Install docker packages
  become: true
  apt:
    name: 
      - docker.io 
      - docker-compose
    state: present
    update_cache: yes

- name: Install docker
  pip:
    name: docker

- name: Create default network
  become: true
  community.docker.docker_network:
    name: netty
    state: present
