---
- name: Install python packages
  become: true
  apt:
    name: 
      - python3 
      - python3-pip
    state: present
    update_cache: yes
    
- name: Add ~/.local/bin to .bashrc
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export PATH="\$PATH:~\/\.local\/bin.*'
    line: 'export PATH="$PATH:~/.local/bin"'
    state: present