---
- name: Check exists
  stat:
    path: ~/.cargo
  register: cargo_stat

- name: Download rustup
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.rs
  when: not cargo_stat.stat.exists

- name: Make executable
  file:
    path: /tmp/rustup.rs
    mode: '777'
  when: not cargo_stat.stat.exists

- name: Install rust
  shell:
    cmd: '/tmp/rustup.rs -y'
  when: not cargo_stat.stat.exists

- name: Add ~/.cargo/bin to .bashrc
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export PATH="\$PATH:~\/\.cargo\/bin.*'
    line: 'export PATH="$PATH:~/.cargo/bin"'
    state: present