---
- name: Check exists
  stat:
    path: ~/dotnet
  register: dotnet_stat

- name: Download dotnet script
  get_url:
    url: https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
    dest: /tmp/dotnet-install.sh
  when: not dotnet_stat.stat.exists

- name: Make executable
  file:
    path: /tmp/dotnet-install.sh
    mode: '777'
  when: not dotnet_stat.stat.exists

- name: Install nvm
  shell:
    cmd: '/tmp/dotnet-install.sh --channel {{ versions.dotnet }} --install-dir ~/dotnet --os linux'
  when: not dotnet_stat.stat.exists

- name: Add ~/dotnet to .bashrc
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export PATH="\$PATH:$HOME\/\dotnet.*'
    line: 'export PATH="$PATH:$HOME/dotnet"'
    state: present