---
- name: Add user
  become: true
  user:
    name: "{{ user.name }}"
    state: present
    generate_ssh_key: yes
    append: yes
    groups:
      - docker
      - sudo
  
- name: Add sudo rights
  become: true
  lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ user.name }}"
    line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: 'visudo -cf %s'

- name: Update SSH authorized keys
  become: true
  lineinfile:
    dest: "/home/{{ user.name }}/.ssh/authorized_keys"
    line: "{{ item.line }}"
    owner: "{{ user.name }}"
    state: present
  with_items:
    - line: "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIIyvvK3MHiUcC8hSSVGtgXiyT+IDeG+4Dm1+i7uLu/ZtAAAABHNzaDo="
    - line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGVigDawGVavWoRBeBfGBju9q5GVWHlgYK/5udQhLOci4WmjXomw8tmKdYWl2J1jit+274R/hAYL1ysayTNeaKsX9josJIdTAvQ6+3Bej/piYPc14VLbjSOc4ov99mjyveWk31UOKyW96JC0ioHZYk60DiEB9s66PjOLAlmLJWSrA1L/+s2gtbM9FmDjboKIpNTAyuAVRzejIWymIaJiU2O3RLdxZhc5PNxU4Lo6OMGf4ecLbwkHuyQy/o0WbCBUlSIcoDXRhTNceZmE9/KYOhcL/sBel4j5EfyAzZtlEN7+GRKKdwVwxDwdyVGaiHx7Zqvcdh3hH/fk+K3bNc6WIDv9Lp3VQN1WY+AxlxIzoC79fhKwUQwjBQ88Jk4Wa0dTR5HweqYQ4ii9jfULN74aYi8ockBHL2gRNGri85tvV3KiHmcJED0qLPhxgDDpAi8rX94tnD8rmyRrR2DqfoGAjdsn8CMQZ/RiB2UclkW9dSGsjV6AuUt817X6K3tnKIBplHVzThUTckYu49bdJRGFsifj5rbn27/OxSTeo6H1+Dbo6ytftNIZueXKZb8LeCRPO+IiFJFQ5ATWPms6sXn93itJqiHK1fOWJL1EomoroNdT0El84dU//q9gpUuuIzPhy8bhNZe2O6ZRuFdaIZpqJ4TOeJhdCf0BetWnxuGPq9YQ== chris"