theme: jekyll-theme-minimal
source: .
destination: _site
exclude:
- Gemfile
- Gemfile.lock
- nginx.conf
- node_modules/
- .devcontainer/
permalink: /:categories/:year-:month-:day-:title.html
collections:
    projects:
        name: projects
        output: true
        permalink: "/projects/:path"
kramdown:
    syntax_highlighter_opts:
        line_numbers: false
        tab_width: 2
        css: class
imagesurl: "/assets/gallery/imgs/"
thumbsurl: "/assets/gallery/thumbs/"
repository: weavc/weavc
url: "https://www.weav.ovh"
plugins:
  - jekyll-sitemap
