# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll"
gem 'github-pages', group: :jekyll_plugins
# gem "rails"

gem "webrick", "~> 1.8"
gem 'kramdown-parser-gfm', group: :jekyll_plugins
gem 'jekyll-theme-minimal', group: :jekyll_plugins 
gem 'jekyll-sitemap', group: :jekyll_plugins
