# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll"
gem 'kramdown-parser-gfm', group: :jekyll_plugins
gem 'jekyll-theme-minimal', group: :jekyll_plugins 
gem 'jekyll-sitemap', group: :jekyll_plugins
