name: Docker Build and Push

on:
  push:
    branches: 
      - master
    paths: 
      - 'docs/**'
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Web
        uses: docker/build-push-action@v2
        with:
          context: docs/
          file: docs/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/chrisweaver1/blog:latest

