name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master", "testing/*"]
    paths: 
      - 'docs/**'
      - '.github/workflows/jekyll.yml'
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
  
defaults:
  run:
    working-directory: ./docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
          
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        
      - name: Build with Jekyll
        run: |
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          
      - name: Debugging
        run: ls -al
        
      - name: Upload artifact
        uses: weavc/upload-pages-artifact@resolve-correct-path
