name: Ruby Build

on: 
  push:
    branches:
    - 'master'
    paths: 
      - 'docs/**'
  pull_request:
    branches:
    - '*'
    paths: 
      - 'docs/**'
      - '.github/workflows/ruby.yml'

defaults:
  run:
    working-directory: ./docs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Dependancies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        npm install
        
    - name: Dependancies
      run: npm run build
